on:
  push:
    branches:    
      - master
  pull_request:
    branches:    
      - master
name: Deploy
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@master
    - name: Clean
      uses: heowc/action-hexo@master
      with:
        args: clean
    - name: Generate
      uses: heowc/action-hexo@master
      with:
        args: generate
    - name: Deploy
      uses: heowc/action-hexo@master
      env:
        EMAIL: yulhuang@cisco.com
        NAME: yulhuang
      with:
        args: deploy