name: Deploy Blog

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: "10.x"
    - name: Setup Hexo env
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.deploy }}
      run: |
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name 'yulhuang'
        git config --global user.email 'yulhuang@cisco.com'
        npm i -g hexo-cli
        npm i
    - name: Deploy
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.deploy }}
      run: |
        hexo clean && hexo generate && hexo deploy
