name: Deploy Blog

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: "10.x"
    - name: Setup Hexo env
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.deploy }}
      run: |
        npm i -g hexo-cli
        npm i
    - name: Deploy
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.deploy }}
      run: |
        hexo clean && hexo generate && hexo deploy
